# Generated by Django 3.0.1 on 2019-12-26 16:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='име')),
                ('slug', models.SlugField(allow_unicode=True, verbose_name='охлюв')),
                ('weight', models.PositiveSmallIntegerField(verbose_name='тежест')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='създадена')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='последна промяна')),
            ],
            options={
                'verbose_name': 'рубрика',
                'verbose_name_plural': 'рубрики',
                'ordering': ('-weight',),
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.DateField(default=datetime.date.today, verbose_name='дата на издаване')),
                ('number', models.PositiveSmallIntegerField(unique_for_year='published', verbose_name='номер на броя')),
                ('online', models.BooleanField(verbose_name='онлайн')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='създаден')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='последна промяна')),
            ],
            options={
                'verbose_name': 'брой',
                'verbose_name_plural': 'броеве',
                'get_latest_by': 'published',
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=50, verbose_name='ключова дума')),
                ('slug', models.SlugField(allow_unicode=True, verbose_name='охлюв')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='създадена')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='последна промяна')),
            ],
            options={
                'verbose_name': 'ключова дума',
                'verbose_name_plural': 'ключови думи',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='заглавие')),
                ('slug', models.SlugField(allow_unicode=True, verbose_name='охлюв')),
                ('subtitle', models.CharField(blank=True, max_length=200, verbose_name='подзаглавие')),
                ('text', models.TextField(verbose_name='текст')),
                ('block', models.SmallIntegerField(choices=[(-1, '− (не е на първа страница)'), (0, 'горе вляво'), (1, 'горе по средата и вдясно'), (2, 'долу вляво'), (3, 'горното средно'), (4, 'долното средно'), (5, 'долу вдясно'), (6, 'най-долу по средата')], default=-1, verbose_name='блокче')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='създадена')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='последна промяна')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='news.Category', verbose_name='рубрика')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='news.Issue', verbose_name='брой')),
                ('keywords', models.ManyToManyField(blank=True, to='news.Keyword', verbose_name='ключови думи')),
            ],
            options={
                'verbose_name': 'статия',
                'verbose_name_plural': 'статии',
                'unique_together': {('issue', 'slug')},
            },
        ),
    ]
