# Generated by Django 3.0.1 on 2019-12-29 16:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('order',), 'verbose_name': 'статия', 'verbose_name_plural': 'статии'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('order',), 'verbose_name': 'рубрика', 'verbose_name_plural': 'рубрики'},
        ),
        migrations.AlterModelOptions(
            name='keyword',
            options={'ordering': ('order',), 'verbose_name': 'ключова дума', 'verbose_name_plural': 'ключови думи'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='weight',
        ),
        migrations.AddField(
            model_name='article',
            name='authors',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='автори'),
        ),
        migrations.AddField(
            model_name='article',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='пореден номер'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='пореден номер'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='keyword',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='пореден номер'),
            preserve_default=False,
        ),
    ]
