# Generated by Django 3.0.1 on 2020-01-07 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20191229_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='truncate_after',
            field=models.PositiveSmallIntegerField(default=100, verbose_name='отрязване след дума'),
        ),
    ]
