# Generated by Django 3.0.3 on 2020-06-03 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20200125_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_extra',
            field=models.BooleanField(default=False, help_text='Ако една статия е отбелязана като притурена към броя си, тогава датата ѝ на издаване е датата ѝ на създаване вместо датата на издаване на броя ѝ.', verbose_name='притурена'),
        ),
    ]
