# Generated by Django 3.0.7 on 2020-06-28 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='', verbose_name='охлюв'),
            preserve_default=False,
        ),
    ]
