# Generated by Django 3.1.2 on 2021-04-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_profile_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='%Y/%m/', verbose_name='файл')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='създаден')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='последна промяна')),
            ],
            options={
                'verbose_name': 'изображение',
                'verbose_name_plural': 'изображения',
            },
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, verbose_name='животоописание'),
        ),
    ]
